### ISSUE TITLE
Duplicate images of lord collection

### ISSUE THREAD

**Issue by sethhiker** [botcar/botcar-data#18]
In "Images of Lord's herbarium specimens from the Sloane Herbarium", some images are duplicated.
images urn=urn:cite:fufolioimg:BotCarLord.Lord_HS267_074_2251 and urn=urn:cite:fufolioimg:BotCarLord.Lord_HS267_074_2252 are duplicated on 
http://folio.furman.edu/citeservlet/browseimg?urn=urn:cite:fufolioimg:BotCarLord
Upon inspection  HS267_074_2252 is the better image and the duplicate should be resolved.

Also, 268_1 has 4 images: urn:cite:fufolioimg:BotCarLord.Lord_HS268_001_2248 ,249,250, 254.
look at them to see what the differences are and resolve duplicates

**Comment by Eumaeus** [comment]
We have duplicates when there were doubts as to the quality of the first image. I think this is okay.
